# Generated by Django 6.0.3 on 2026-03-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Venta'), ('rent', 'Renta')], default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'Casa'), ('land', 'Terreno'), ('apartment', 'Departamento')], default='house', max_length=20),
        ),
    ]
