# Generated by Django 6.0.3 on 2026-03-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_video_property_video_url_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='measures',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
