# Generated by Django 6.0.3 on 2026-03-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_folio_property_google_maps_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lot_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_lots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
