# Generated by Django 6.0.3 on 2026-04-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_lot_price_property_total_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
