# Generated by Django 6.0.3 on 2026-04-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='credit_type',
            field=models.CharField(choices=[('none', 'Ninguno'), ('infonavit', 'INFONAVIT'), ('fovissste', 'FOVISSSTE'), ('both', 'INFONAVIT y FOVISSSTE')], default='none', max_length=10),
        ),
    ]
