# Generated by Django 6.0.3 on 2026-04-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_credit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
