# Generated by Django 6.0.3 on 2026-04-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_property_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'Casa'), ('land', 'Terreno'), ('apartment', 'Departamento'), ('lots', 'Lotes'), ('hectares', 'Hectáreas'), ('ranch', 'Rancho')], default='house', max_length=20),
        ),
    ]
