# Generated by Django 6.0.3 on 2026-04-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_hectare_price_property_total_hectares'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='custom_financing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_financing_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
